void	app(SOCKET socket);
void	send_message(SOCKET socket, char *buffer);
int	receive_message(SOCKET socket, char *buffer);
void	cleanMsg(char *buffer, char *msg);
char	*getname(size_t namesize);
static void	init(void);
static void	end(void);
void	arg(int argc, char **argv);
int	init_connection(char **argv);
void	title(void);
